# Instrucciones
# =============
#
# Su tarea ya esta compilada con la opcion -g, que es necesaria para
# que use gdb y ddd para depurar los errores de programacion.
#
# Para borrar todos los archivos generados (incluyendo binarios):
# $ make clean

CFLAGS= -g -Wall -pedantic -std=c99
LDFLAGS= -g

all: test-desplazar2

test-desplazar2: test-desplazar2.o desplazar.o
test-delplazar.o desplazar.o: desplazar.h

clean:
	rm -f *.o
	rm -f test-desplazar
