# Instrucciones
# =============
#
# Su tarea ya esta compilada con la opcion -g, que es necesaria para
# que use gdb y ddd para depurar los errores de programacion.
#
# Para borrar todos los archivos generados (incluyendo binarios)
# $ make clean

CFLAGS= -g -Wall -pedantic -std=c99
LDFLAGS= -g

all: lifegame decode-args

clean:
	rm -f *.o
	rm -f lifegame decode-args
